### ISSUE TITLE
Can have only one OTAP setting in applications

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/MxPushNotifications#29]
On the current module, allows you to have multiple settings in the system. for OTAP

However when multiple settings for different environment in the database the widget will not work.

The following line of code check that it will have one setting.
https://github.com/mendix/MxPushNotifications/blob/master/src/pushNotifications/widget/pushNotifications.js#L109

However the constraint is not enforced from within the widget, probably the following line would have some qualification on OTAP, based on a contant, or setting from the modeler

https://github.com/mendix/MxPushNotifications/blob/master/src/pushNotifications/widget/pushNotifications.js#L101

**Comment by simo101** [comment]
Yes you have to add the constraint in the widget to retrieve the correct setting you want. I usually add the constraint enabled.

**Comment by sjoerdbreur** [comment]
There's a similar issue when the GCM service is restarted after sending a message fails, since in that flow a retrieve is used which just takes the first object. (which if multiple objects exist, may not be the correct one)

**Comment by sjoerdbreur** [comment]
Hi all,

We're currently discussing on how to solve this issue, which we consider part of a number of configuration issues where the module could use some improvement:
* As highlighted in this issue, part of the application is set up to support multiple settings objects (per service) in combination with the DTAP mode feature. (Which will create a new settings object if none can be found for the current detected DTAP mode.) However, in several places in the module, the assumption is still made that the settings object is a singleton, and no constraints are applied on the retrieval XPath.
* The DTAP mode detection is currently not very robust, since it just looks if the URL contains 'localhost', 'accp' or 'test', which could be improved upon. (Let's say you create an app 'Point Estimation', it will be deployed to pointestimation.mxapps.io, and any environment would be considered a test environment.)
* There is no way to fully disable notifications for an environment outside of (intentionally) incorrectly configuring the services.

Considering DTAP mode makes the module more complicated and more difficult to use for less experienced users, we propose replacing it with environment constants, as detailed below. However we'd like to hear opinions on how this would affect existing implementations of the module as well:
* The settings object for each service becomes a singleton, and DTAP mode as concept is removed.
* Instead, the settings objects (for each service) are ensured on startup and updated with the values from a series of environment constants which together determine the configuration for each service.
* Implementing this for APNs is a little trickier, since it requires a p12 certificate to authenticate with the service. One possible way around this would be:
	* Store the p12 certificate in the resources folder
	* Specify the relative location to the app basepath in a constant. (In this case this would be '/model/resources/mycertificate.p12')
	* In the startup flow while updating the settings, the file would be retrieved based on this constant, and stored in the APNCertificate FileDocument.
* Introduce a boolean constant ('PushNotificationsActive' or similar) which prevents any push notifications from being sent or queued while set to false.

Your thoughts?

**Comment by RCatersels** [comment]
I can live with that. Good sollution.
