### ISSUE TITLE
404 - file not found for file: js/jquerymin.js

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#3]
As soon as I place the widget in the pages the application fails to work. I just get the screen refresh icon. From the console I see multiple 404 - file not found for file: js/jquerymin.js errors. 

I have placed the components.json in the main of the theme folder.
{"files":{"css":["lib/bootstrap/css/bootstrap.min.css","mxclientsystem/mxui/ui/mxui.css","css/theme.css"],"js":["mxclientsystem/mxui/mxui.js", "js/jquerymin.js","widgets/pushNotifications/lib/PushNotification.js"]},"cachebust":"635629815280143905"}
I assume it can not find the jquerymin.js. I do have a jquery-1.11.2.min.js in the library. Something in the naming?

Regards,

Ronald

**Comment by RCatersels** [comment]
Changing the components.js does not help. I then get 404 - file not found for file: js/jquery-1.11.2.min.js

**Comment by simo101** [comment]
The components file will need to reference a jquery library. It doesn't have to be jquerymin.js. The current components file assumes that you will have a folder in your theme folder called js and inside it there will be a file called jquerymin.js. Make sure the folder js/ is in the theme folder and you have the js/jquery-1.11.2.min.js loaded. The reason we need to do this is because jquery needs to be globally accessible for the widget to work. I did look at including the jquery import in the widget, but due to the functions being called outside of the widget this didn't seem to work.

**Comment by RCatersels** [comment]
Error is gone now. One question though, when I start the app in 'View hybrid mobile app' al is working while when I try the 'View phone app' all I get is the refresh icon after I am logging in. At the one side I can understand this, but can you confirm that the only way of testing the module is either the hybrid mode or by passing the apple / google store hoops? We are in the process of getting the developer accounts and doing the rest of the process, but this probably will take another couple of days.

**Comment by simo101** [comment]
The only way to test this is to use an actual phonegap build app installed on a ios or android device. The reason for this is because by default Mendix doesn't include the push plugin in the developer app.  I would suggest following the build guidline on this documentation and install it on an android device. For development you do not need to have certificates. You can use an emulator to test it. 

It shouldn't have an infinite progress bar though. It should just ignore if the plugin isn't found. I will try to look into this issue.
