### ISSUE TITLE
Duplicate device entries when using push notifications

### ISSUE THREAD

**Issue by MulderWH** [mendix/MxPushNotifications#50]
Hi, when using a mobile mendix app with push notifications your mobile device is registered to receive notifications. This results in a new entry in the database with your registration id. If you reinstall the mobile app the system will create another entry in the db with a different registration id.

This means the user has now two entries in the database. Then if you send a new push notification to the user, the system will create two messages (one for each device registration). The behavior I suspect is one entry for each device, and a user can have zero or more devices.

**Comment by KevinVlaanderen** [comment]
The behavior you are describing is actually intended. The way Registration/Device IDs work, for both Android and iOS, is that they serve as an identifier for a device/appInstance combination. This means that they can (and will) occasionally be re-generated, e.g. when you re-install the app or when device/system configuration changes. As such, registration IDs should not be used to identify devices over time. Instead, a registration ID should be fetched every time you start the app (the push notifications widget does this for you).

In order to clean up registration IDs, each platform uses its own approach. For Android, sending a message to an invalid registration ID will result in a response payload that tells you what to do with it; change it to another ID, or remove it from your database.
The PushNotifications module will take care of this for you by handling the response payload.

For iOS, at least for the version of APNS that this module supports, you can make use of a feedback service. This service will tell you for a given ID whether it's still valid.
The PushNotifications module contains a scheduled event that should take care of this.

**Comment by MulderWH** [comment]
Thanks Kevin for the answer.
